spring.application.name=Borrowhen
server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d4b7vkmr433s7396uvt0-a.singapore-postgres.render.com/borrow_when_db_2?sslmode=require
spring.datasource.username=borrow_when_db_2_user
spring.datasource.password=c3zKXZTdfE37R9q7mIxctvxAoqKO2DRl
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

user.max.display = 10
inventory.max.display = 10


cipher.algorithm=AES
cipher.key=Th3W0r!dbE!0n9$T0g1@2etH3tr*eg0E

stripe.api.key=qweq

